### ISSUE TITLE
console.log UTF-8 characters

### ISSUE THREAD

**Issue by vilnius-leopold** [crcn-archive/sardines#15]
I'm running Linux (Ubuntu 15.04) and nexe version 0.4.1.
When compiling and running this piece of code the utf8 characters are not printed to the terminal.

``` javascript
console.log('Some utf8 chars █ ◾ ▌');
```

Output:

``` txt
Some utf8 char   
```

**Comment by crcn** [comment]
This library is no longer maintained. Please use Browserify or Webpack instead!
